# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='adjunto1',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/%Y/%m/%d/1450366000'),
        ),
        migrations.AlterField(
            model_name='email',
            name='asunto',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
