# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20151218_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='adjunto1',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/%Y/%m/%d/1450704438'),
        ),
        migrations.AlterField(
            model_name='email',
            name='correo',
            field=models.EmailField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo_envio',
            field=models.CharField(choices=[(b'aceptacion', b'aceptacion'), (b'env\xc3\xado dte', b'env\xc3\xado dte'), (b'notificacion', b'notificacion'), (b'rechazo', b'rechazo'), (b'rems', b'rems')], db_index=True, max_length=20),
        ),
    ]
