# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20151221_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='id_envio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='adjunto1',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/%Y/%m/%d/1450705080'),
        ),
    ]
