# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_auto_20151228_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='adjunto1',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/%Y/%m/%d/1453818803'),
        ),
        migrations.AlterField(
            model_name='email',
            name='id_envio',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
