# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_auto_20160801_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='pdf',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/pdf/%Y/%m/%d/1472587948'),
        ),
        migrations.AddField(
            model_name='email',
            name='xml',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/xml/%Y/%m/%d/1472587948'),
        ),
        migrations.AlterField(
            model_name='email',
            name='adjunto1',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/%Y/%m/%d/1472587948'),
        ),
        migrations.AlterField(
            model_name='email',
            name='estado_documento',
            field=models.CharField(blank=True, choices=[(b'Pendiente env\xc3\xado a SII', b'Pendiente env\xc3\xado a SII'), (b'Enviando a SII', b'Enviando a SII'), (b'Enviado a SII', b'Enviado a SII'), (b'Aceptado OK SII', b'Aceptado OK SII'), (b'Aceptado con reparo SII', b'Aceptado con reparo SII'), (b'Pendiente reenv\xc3\xado a SII', b'Pendiente reenv\xc3\xado a SII'), (b'No aplica env\xc3\xado a SII', b'No aplica env\xc3\xado a SII'), (b'No recibido por SII', b'No recibido por SII'), (b'Error env\xc3\xado SII', b'Error env\xc3\xado SII'), (b'Rechazado SII', b'Rechazado SII'), (b'Anulado Manual', b'Anulado Manual'), (b'Problemas al encontrar el archivo', b'Problemas al encontrar el archivo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo_envio',
            field=models.CharField(choices=[(b'aceptacion', b'Aceptacion'), (b'envio dte', b'Envio DTE'), (b'notificacion', b'Notificacion'), (b'rechazo', b'Rechazo'), (b'rems', b'Rems')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo_operacion',
            field=models.CharField(blank=True, choices=[(b'compra', b'Compra'), (b'venta', b'Venta')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo_receptor',
            field=models.CharField(blank=True, choices=[(b'electronico', b'Electronico'), (b'manual', b'Manual'), (b'ambos', b'Ambos')], max_length=100, null=True),
        ),
    ]
