# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-30 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_auto_20160830_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='adjunto1',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/ad1/%Y/%m/%d/1472588998'),
        ),
        migrations.AlterField(
            model_name='email',
            name='estado_documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='pdf',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/pdf/%Y/%m/%d/1472588998'),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo_envio',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo_operacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='tipo_receptor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='xml',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b'adjuntos/xml/%Y/%m/%d/1472588998'),
        ),
    ]
