# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLogEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField(auto_now_add=True)),
                ('correo', models.EmailField(max_length=250)),
                ('numero_folio', models.BigIntegerField()),
                ('tipo_dte', models.IntegerField()),
                ('rut_emisor', models.CharField(max_length=250)),
                ('resolucion_emisor', models.BigIntegerField()),
                ('fecha_evento', models.BigIntegerField()),
                ('nombre_evento', models.CharField(max_length=250)),
            ],
        ),
    ]
