# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0002_emaillogevent_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillogevent',
            name='resolucion_emisor',
            field=models.BigIntegerField(null=True),
        ),
    ]
