application: django-tracking
version: 1
runtime: python27
api_version: 1
threadsafe: yes

instance_class: F4_1G

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /static
  static_dir: static
- url: .*
  script: app.wsgi.application

libraries:
- name: MySQLdb
  version: "latest"
- name: PIL
  version: "latest"