# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendgridConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(db_index=True, max_length=200)),
                ('api_user', models.CharField(db_index=True, max_length=200)),
                ('api_pass', models.CharField(db_index=True, max_length=200)),
                ('asunto_email_dte', models.EmailField(db_index=True, max_length=240)),
                ('nombre_email_dte', models.CharField(db_index=True, max_length=200)),
                ('asunto_email_reporte', models.EmailField(db_index=True, max_length=240)),
                ('nombre_email_reporte', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateReporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte_url', models.URLField(blank=True, db_index=True)),
                ('asunto_reporte', models.CharField(db_index=True, max_length=240)),
                ('template_html', models.TextField()),
            ],
        ),
    ]
