# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_eliminacionhistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoapWebService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('con_autenticacion', models.BooleanField(default=False)),
                ('usuario_autenticacion', models.CharField(blank=True, max_length=200, null=True)),
                ('clave_autenticacion', models.CharField(blank=True, max_length=200, null=True)),
                ('con_objeto_documento', models.BooleanField(default=False)),
                ('nombre_objeto_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('nombre_parametro_documento', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_objeto_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_objeto_documento', models.CharField(blank=True, max_length=255, null=True)),
                ('solo_default', models.BooleanField(default=False)),
                ('metodo_default', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_default', models.CharField(blank=True, help_text=b'Lista de parametros ordenados                                           por posici\xc3\xb3n en el metodo del Web Service                                           separado por ; sin espacios ejemplo: \t\t\t\t\t\t\t\t\t\t  "rut_emisor;numero_folio;input_date"', max_length=255)),
                ('campos_default', models.CharField(blank=True, max_length=255, null=True)),
                ('con_procesado', models.BooleanField(default=False)),
                ('metodo_procesado', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_procesado', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_procesado', models.CharField(blank=True, max_length=255, null=True)),
                ('con_enviado', models.BooleanField(default=False)),
                ('metodo_enviado', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_enviado', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_enviado', models.CharField(blank=True, max_length=255, null=True)),
                ('con_leido', models.BooleanField(default=False)),
                ('metodo_leido', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_leido', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_leido', models.CharField(blank=True, max_length=255, null=True)),
                ('con_rebotado', models.BooleanField(default=False)),
                ('metodo_rebotado', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_rebotado', models.CharField(blank=True, max_length=255, null=True)),
                ('campos_rebotado', models.CharField(blank=True, max_length=255, null=True)),
                ('con_rechazado', models.BooleanField(default=False)),
                ('metodo_rechazado', models.CharField(blank=True, max_length=200, null=True)),
                ('parametros_rechazado', models.CharField(blank=True, max_length=200, null=True)),
                ('campos_rechazado', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
