# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_soapwebservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_row_max_length', models.IntegerField()),
            ],
        ),
    ]
