# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_auto_20160219_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soapwebservice',
            old_name='parametros_eviado',
            new_name='parametros_enviado',
        ),
        migrations.AddField(
            model_name='soapwebservice',
            name='campos_default',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soapwebservice',
            name='campos_enviado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soapwebservice',
            name='campos_leido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soapwebservice',
            name='campos_parametros_procesados',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soapwebservice',
            name='campos_rebotado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='soapwebservice',
            name='campos_rechazado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
