# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_generalconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='soapwebservice',
            name='con_objeto_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soapwebservice',
            name='nombre_objeto_request',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
