# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0005_auto_20160219_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soapwebservice',
            old_name='campos_parametros_procesados',
            new_name='campos_procesado',
        ),
    ]
