# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0006_generalconfiguration_report_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='report_file_zipped',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='generalconfiguration',
            name='report_file_format',
            field=models.CharField(choices=[(b'xlsx', b'xlsx'), (b'csv', b'csv'), (b'tsv', b'tsv')], max_length=100),
        ),
    ]
