# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-09 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0007_auto_20160505_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalconfiguration',
            name='events_register',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalconfiguration',
            name='events_to_register',
            field=models.CharField(default=b'processed', max_length=255),
        ),
    ]
