# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20160801_1203'),
        ('configuraciones', '0008_auto_20160509_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliminacionhistorico',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding'),
        ),
        migrations.AddField(
            model_name='generalconfiguration',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding'),
        ),
        migrations.AddField(
            model_name='sendgridconf',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding'),
        ),
        migrations.AddField(
            model_name='soapwebservice',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding'),
        ),
        migrations.AddField(
            model_name='templatereporte',
            name='holding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Holding'),
        ),
    ]
