# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='es_admin',
        ),
    ]
