# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-18 20:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_remove_perfil_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='enable_report',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
