# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(upload_to=b'reportes/%Y/%m/%d/1449753833'),
        ),
    ]
