# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report',
            field=models.FileField(upload_to=b'reportes/%Y/%m/%d/1470067414'),
        ),
    ]
