# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-17 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_auto_20160801_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposOpcionalesEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcional1', models.CharField(db_index=True, max_length=120)),
                ('opcional2', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('opcional3', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresa')),
            ],
        ),
    ]
